# Generated by Django 5.1.1 on 2025-10-17 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('starting_odometer_reading', models.IntegerField()),
                ('is_return_to_same_location', models.BooleanField(default=False)),
                ('driving_type', models.CharField(choices=[('self_drive', 'Self Drive'), ('need_driver', 'Need Driver')], max_length=20)),
                ('no_of_passengers', models.IntegerField()),
                ('fuel_responsibility', models.CharField(choices=[('by_client', 'By Client'), ('by_company', 'By Company')], max_length=20)),
                ('deposited_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_vat_applicable', models.BooleanField(default=False)),
                ('insurance_type', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('general', 'General')], max_length=20)),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat')], max_length=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
                ('dropoff_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dropoff_bookings', to='bookings.location')),
                ('pickup_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_bookings', to='bookings.location')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='BookingAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on_name', models.CharField(max_length=100)),
                ('add_on_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_add_ons',
            },
        ),
        migrations.CreateModel(
            name='BookingExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_return_date', models.DateField()),
                ('extend_return_date', models.DateField()),
                ('no_of_extend_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_extensions',
            },
        ),
        migrations.CreateModel(
            name='BookingReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('final_odometer_reading', models.IntegerField()),
                ('is_damage', models.BooleanField(default=False)),
                ('damage_notes', models.TextField(blank=True, null=True)),
                ('refunded_deposit_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_details', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_returns',
            },
        ),
    ]
